language: dart
sudo: false
dart:
  - stable
dart_task:
  - test
#  - dartanalyzer
# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]
cache:
  directories:
    - $HOME/.pub-cache
env:
  - DB_MONGODB_DB_NAME=documents_test
services:
  - mongodb
before_script:
  - mkdir -p $TRAVIS_BUILD_DIR/var $TRAVIS_BUILD_DIR/var/doc_cache $TRAVIS_BUILD_DIR/var/test_cache
  - chmod -R 777 $TRAVIS_BUILD_DIR/var
