version: '3.1'

services:
  app:
    image: tmannherz/doc-store-base
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
      - "8181:8181"
    environment:
      DB_MONGODB_URI: mongodb://db/
      GCLOUD_PROJECT_FILE: /run/secrets/gcloud_project
      GCLOUD_BUCKET_FILE: /run/secrets/gcloud_bucket
      GCLOUD_SERVICE_ACCOUNT_FILE: /run/secrets/gcloud_service_account
#      SERVER_SSL_CERTIFICATE: /run/secrets/server_ssl_certificate
#      SERVER_SSL_KEY: /run/secrets/server_ssl_key
    secrets:
      - gcloud_project
      - gcloud_bucket
      - gcloud_service_account
#      - server_ssl_certificate
#      - server_ssl_key

  db:
    image: mongo
    restart: always
    volumes:
       - db_data:/data/db

secrets:
  gcloud_project:
    file: docker/gcloud_project.txt
  gcloud_bucket:
    file: docker/gcloud_bucket.txt
  gcloud_service_account:
    file: docker/gcloud_service_account.json
#  server_ssl_certificate:
#    file: docker/dc-doc-store.chain.crt
#  server_ssl_key:
#    file: docker/dc-doc-store.key

volumes:
    db_data: