name: document_store
description: Service to manage file storage in the Google Cloud.
version: 0.0.1
author: Todd Mannherz <todd.mannherz@gmail.com>
homepage: https://github.com/tmannherz/document-store

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args:
  connection_pool:
  cron:
  crypto:
  dart_config:
  dart_ext:
  dbcrypt:
  gcloud:
  googleapis_auth:
  http:
  image:
  mime_types:
  mongo_dart:
  option:
  shelf_auth:
  shelf_exception_handler:
  shelf_route:

dev_dependencies:
  test:
